export const defaultFiltersConfig = {
	columns: [],
	includeAll: true,
	allLabel: 'Tudo',
	mode: 'single',
	match: 'OR',
	labelMap: {},
	defaultValue: null,
	includeCounts: false
};

export const defaultSearchConfig = {
	columns: [],
	placeholder: 'Busque pelo tema ou titulo do video',
	minLength: 0,
	instant: false,
	submitLabel: 'Buscar',
	clearLabel: 'Limpar',
	showClearButton: true,
	suggestionLimit: 6,
	containerPadding: '0.5rem',
	containerPaddingDesktop: null,
	inputBackground: 'transparent',
	inputColor: '#111827',
	inputPlaceholderColor: 'rgba(17,24,39,0.45)',
	inputBorderColor: 'rgba(17,24,39,0.15)',
	inputFocusBorderColor: '#111827',
	inputFocusOutline: '#111827',
	buttonBackground: '#111827',
	buttonColor: '#ffffff',
	buttonHoverBackground: '#0f172a',
	buttonBorderColor: 'transparent',
	buttonHoverBorderColor: 'transparent',
	clearButtonBackground: 'rgba(17,24,39,0.05)',
	clearButtonColor: '#111827',
	clearButtonHoverBackground: 'rgba(17,24,39,0.12)',
	clearButtonBorderColor: 'transparent',
	clearButtonHoverBorderColor: 'transparent',
	modalBackground: 'rgba(6,10,21,0.96)'
};

export const defaultSectionsConfig = {
	column: null,
	order: [],
	labelMap: {},
	fallbackLabel: 'Outros videos',
	highlight: null
};

export const defaultHighlightConfig = {
	column: null,
	values: ['destaque', 'highlight', 'sim', 'true', '1'],
	label: 'Destaque',
	limit: 6,
	retainInSections: false,
	anchor: 'destaque'
};

export const defaultVideoConfig = {
	id: ['video_id', 'id'],
	mobileId: null,
	desktopId: null,
	title: ['titulo', 'title'],
	subtitle: ['subtitulo', 'subtitle'],
	description: ['descricao', 'description'],
	thumbnail: ['poster', 'poster_mobile', 'posterMobile', 'thumb', 'thumbnail', 'imagem', 'image'],
	tag: ['tag', 'tema', 'category'],
	section: ['secao', 'categoria', 'bloco'],
	publishedAt: ['data', 'data_publicacao', 'data_de_publicacao'],
	link: ['link', 'url', 'links'],
	searchTokensExtra: []
};

export const defaultLayoutConfig = {
	stickyOffset: 'var(--sheet-controls-sticky-offset, 0px)',
	showCounts: false,
	highlightLimit: null,
	cardsPerRowMobile: 1,
	cardsPerRowTablet: 2,
	cardsPerRowDesktop: 4,
	backgroundColor: '#fdf4ed',
	mobileTopbarTitle: '',
	desktopTitle: '',
	desktopSubtitle: '',
	mobileTitle: '',
	mobileSubtitle: '',
	subtitle: '',
	desktopTopbarBackground: '#ffffff',
	desktopTopbarColor: '#111827',
	containerMaxWidthDesktop: 'none',
	containerPaddingMobile: '1rem',
	containerPaddingDesktop: '1rem',
	mobileChromeBackground:
		'linear-gradient(180deg, rgba(17,24,39,0.45) 0%, rgba(17,24,39,0.32) 55%, rgba(17,24,39,0.18) 100%)',
	mobileChromeTextColor: null,
	mobileChromeActiveColor: null,
	mobileBottomBarBackground:
		'linear-gradient(180deg, rgba(6,8,18,0.08) 0%, rgba(6,8,18,0.95) 100%)',
	mobileBottomBarButtonBackground: 'rgba(254, 247, 234, 0.92)',
	mobileBottomBarButtonColor: 'rgba(12, 18, 36, 0.78)',
	mobileBottomBarButtonBorderColor: 'rgba(255, 255, 255, 0.08)',
	mobileBottomBarButtonActiveBackground: 'rgba(255, 250, 241, 0.98)',
	mobileBottomBarButtonActiveColor: '#060a15',
	mobileBottomBarShortzBackground: 'rgba(226, 66, 46, 0.08)',
	mobileBottomBarShortzColor: 'rgba(252, 243, 234, 0.95)',
	mobileBottomBarShortzBorderColor: 'rgba(255, 255, 255, 0.16)',
	mobileBottomBarShortzActiveBackground: '#e34832',
	mobileBottomBarShortzActiveColor: '#ffffff',
	cardGap: '12px',
	cardMinWidthDesktop: '240px',
	cardMaxWidthDesktop: '320px',
	enableMobileFeed: true,
	mobileFeedSkipDFP: false,
	mobileDefaultView: 'shortz',
	showVideoMeta: true,
	mobileFeedMaxWidth: 768,
	mobileFeedTitleColor: '#ffffff',
	mobileFeedMetaColor: 'rgba(255,255,255,0.78)',
	mobileFeedTagColor: '#111827',
	mobileFeedTagBackground: 'rgba(255,255,255,0.92)',
	mobileFeedOverlay:
		'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(8,12,24,0.78) 62%, rgba(8,12,24,0.92) 100%)',
	mobileShortzTitleColor: null,
	mobileShortzMetaColor: null,
	mobileShortzTagColor: null,
	mobileFeedGridTitleColor: null,
	mobileFeedGridMetaColor: null,
	mobileSearchTitleColor: null,
	mobileSearchTextColor: null,
	mobileSearchFilterColor: null,
	mobileFeedControlsOffset: '0px',
	mobileIntroEnabled: true,
	mobileIntroTitle: '',
	mobileIntroSubtitle: '',
	mobileIntroIndicatorLabel: '',
	mobileIntroCountdownLabel: '',
	mobileIntroSkipLabel: '',
	mobileIntroBackground: 'linear-gradient(180deg, rgba(8,12,24,0.9) 0%, rgba(8,12,24,0.55) 100%)',
	desktopIntroTitle: '',
	desktopIntroSubtitle: '',
	headingEyebrowDesktop: '',
	headingEyebrowMobile: '',
	headingEyebrowColor: '#c2410c',
	headingDividerColor: 'rgba(194, 65, 12, 0.28)',
	headingAlignmentDesktop: 'center',
	headingAlignmentMobile: 'left',
	mobileFeedHeadingEnabled: true,
	mobileFeedHeadingEyebrow: '',
	mobileFeedHeadingTitle: '',
	mobileFeedHeadingSubtitle: '',
	mobileFeedHeadingBackground: 'transparent',
	mobileFeedHeadingTitleColor: null,
	mobileFeedHeadingSubtitleColor: null,
	mobileFeedHeadingEyebrowColor: null,
	mobileFeedHeadingDividerColor: null,
	mobileFeedHeadingPadding: '1.5rem 1.25rem 1.25rem',
	mobileFeedHeadingBorderRadius: '0',
	mobileFeedHeadingShadow: 'none',
	mobileFeedHeadingAlignment: 'left',
	mobileFeedHeadingGap: '0.5rem',
	mobileFeedHeadingMaxWidth: '100%',
	mobileFeedHeadingDividerWidth: '72px',
	mobileFeedHeadingDividerHeight: '2px',
	mobileFeedHeadingShowDivider: true,
	mobileFeedHeadingEyebrowFontSize: '0.85rem',
	mobileFeedHeadingEyebrowLetterSpacing: '0.18em',
	mobileFeedHeadingEyebrowFontWeight: '600',
	mobileFeedHeadingEyebrowFontFamily: null,
	mobileFeedHeadingEyebrowTransform: 'uppercase',
	mobileFeedHeadingTitleFontSize: '1.65rem',
	mobileFeedHeadingTitleLineHeight: '1.2',
	mobileFeedHeadingTitleFontWeight: '700',
	mobileFeedHeadingTitleLetterSpacing: '-0.01em',
	mobileFeedHeadingTitleFontFamily: null,
	mobileFeedHeadingSubtitleFontSize: '1rem',
	mobileFeedHeadingSubtitleLineHeight: '1.45',
	mobileFeedHeadingSubtitleFontWeight: '400',
	mobileFeedHeadingSubtitleLetterSpacing: '0',
	mobileFeedHeadingSubtitleFontFamily: null,
	searchMaxWidthDesktop: '100%',
	controlsHeadingColorDesktop: '#b91c1c',
	controlsHeadingSubtitleDesktop: 'rgba(15, 23, 42, 0.65)',
	controlsHeadingColorMobile: '',
	controlsBackground: 'var(--sheet-background, #fdf4ed)',
	controlsBorderColor: 'transparent',
	controlsShadow: 'none',
	controlsBackdrop: 'none',
	controlsFloatingOffset: null,
	controlsStartMuted: true,
	controlsAutoMute: true,
	sectionTitleColor: '#111827',
	sectionTitleHighlightColor: '#b45309',
	sectionTitleFontSizeMobile: null,
	sectionTitleFontSizeDesktop: null,
	sectionCountColor: 'rgba(15, 23, 42, 0.6)',
	filterChipBackground: 'rgba(15, 23, 42, 0.06)',
	filterChipColor: 'rgba(15, 23, 42, 0.82)',
	filterChipBorderColor: 'transparent',
	filterChipHoverBackground: 'rgba(15, 23, 42, 0.12)',
	filterChipHoverBorderColor: null,
	filterChipActiveBackground: '#0f172a',
	filterChipActiveColor: '#ffffff',
	filterChipActiveBorderColor: '#0f172a',
	filterChipFontSizeMobile: null,
	filterChipFontSizeDesktop: null,
	filterChipCountColor: null,
	videoTitleColor: '#111827',
	videoTitleFontSizeMobile: null,
	videoTitleFontSizeDesktop: null,
	videoTitleFontSizeMobileGrid: null,
	videoSubtitleColor: 'rgba(15, 23, 42, 0.75)',
	videoSubtitleFontSizeMobile: null,
	videoSubtitleFontSizeDesktop: null,
	videoTagBackground: 'rgba(15, 23, 42, 0.08)',
	videoTagColor: 'rgba(15, 23, 42, 0.78)',
	videoTagFontSizeMobile: null,
	videoTagFontSizeDesktop: null,
	desktopOverlayVariant: 'glass',
	desktopOverlayBackdrop:
		'radial-gradient(circle at top left, rgba(80, 132, 247, 0.24), transparent 55%), radial-gradient(circle at bottom right, rgba(236, 72, 153, 0.18), transparent 50%), rgba(5,9,18,0.78)',
	desktopOverlayBackdropBlur: '28px',
	desktopOverlaySurface: 'rgba(12, 18, 36, 0.55)',
	desktopOverlaySurfaceImage: '',
	desktopOverlaySurfaceImageSize: 'cover',
	desktopOverlaySurfaceImagePosition: 'center',
	desktopOverlaySurfaceImageRepeat: 'no-repeat',
	desktopOverlaySurfaceImageBlendMode: 'normal',
	desktopOverlaySurfaceBlur: '22px',
	desktopOverlaySurfaceBorder: 'rgba(255, 255, 255, 0.18)',
	desktopOverlaySurfaceShadow: '0 32px 80px rgba(5, 8, 25, 0.65)',
	desktopOverlayAccent:
		'linear-gradient(135deg, rgba(236, 72, 153, 0.32) 0%, rgba(59, 130, 246, 0.32) 35%, rgba(45, 212, 191, 0.25) 100%)',
	desktopOverlayPlayerBackground: 'rgba(5, 9, 18, 0.88)',
	desktopOverlayMetaAlign: 'center',
	desktopOverlayPlayerPadding: '0rem',
	desktopOverlayCardBackground:
		'linear-gradient(145deg, rgba(9, 14, 26, 0.95) 0%, rgba(17, 25, 46, 0.82) 100%)',
	desktopOverlayCardShadow: '0 32px 64px rgba(5, 9, 18, 0.58)',
	desktopOverlayCardPadding: '1.85rem',
	desktopOverlayCardRadius: '1.8rem',
	desktopOverlayCardMediaPadding: '1.1rem',
	desktopOverlayCardWidth: 'min(560px, 92vw)'
};
